version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: golang-lambda-deployer
    main: ./deployer/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

release:
  github:
    owner: alex-roman
    name: golang-lambda-deployer

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
